<?php

return [
    'age_categories' => ['4-6', '7-10', '11-14', '15-18', '19-64', '65-74', '75+'],

    'default_intake_profiles' => [
        '4-6_male' => [
            'energy_kcal' => 1482,
            'protein' => 19.7,
            'total_fat' => 58,
            'saturated_fat' => 18,
            'salt' => 3,
            'fibre' => 17.5,
        ],
        '4-6_female' => [
            'energy_kcal' => 1378,
            'protein' => 19.7,
            'total_fat' => 54,
            'saturated_fat' => 17,
            'salt' => 3,
            'fibre' => 17.5,
        ],
        '7-10_male' => [
            'energy_kcal' => 1817,
            'protein' => 28.3,
            'total_fat' => 71,
            'saturated_fat' => 22,
            'salt' => 5,
            'fibre' => 20,
        ],
        '7-10_female' => [
            'energy_kcal' => 1703,
            'protein' => 28.3,
            'total_fat' => 66,
            'saturated_fat' => 21,
            'salt' => 5,
            'fibre' => 20,
        ],
        '11-14_male' => [
            'energy_kcal' => 2500,
            'protein' => 42.1,
            'total_fat' => 97,
            'saturated_fat' => 31,
            'salt' => 6,
            'fibre' => 25,
        ],
        '11-14_female' => [
            'energy_kcal' => 2000,
            'protein' => 41.2,
            'total_fat' => 78,
            'saturated_fat' => 24,
            'salt' => 6,
            'fibre' => 25,
        ],
        '15-18_male' => [
            'energy_kcal' => 2500,
            'protein' => 55.2,
            'total_fat' => 97,
            'saturated_fat' => 31,
            'salt' => 6,
            'fibre' => 30,
        ],
        '15-18_female' => [
            'energy_kcal' => 2000,
            'protein' => 45,
            'total_fat' => 78,
            'saturated_fat' => 24,
            'salt' => 6,
            'fibre' => 30,
        ],
        '19-64_male' => [
            'energy_kcal' => 2500,
            'protein' => 55.5,
            'total_fat' => 97,
            'saturated_fat' => 31,
            'salt' => 6,
            'fibre' => 30,
        ],
        '19-64_female' => [
            'energy_kcal' => 2000,
            'protein' => 45,
            'total_fat' => 78,
            'saturated_fat' => 24,
            'salt' => 6,
            'fibre' => 30,
        ],
        '65-74_male' => [
            'energy_kcal' => 2342,
            'protein' => 53.3,
            'total_fat' => 91,
            'saturated_fat' => 29,
            'salt' => 6,
            'fibre' => 30,
        ],
        '65-74_female' => [
            'energy_kcal' => 1912,
            'protein' => 46.5,
            'total_fat' => 74,
            'saturated_fat' => 23,
            'salt' => 6,
            'fibre' => 30,
        ],
        '75+_male' => [
            'energy_kcal' => 2294,
            'protein' => 53.3,
            'total_fat' => 89,
            'saturated_fat' => 28,
            'salt' => 6,
            'fibre' => 30,
        ],
        '75+_female' => [
            'energy_kcal' => 1840,
            'protein' => 46.5,
            'total_fat' => 72,
            'saturated_fat' => 23,
            'salt' => 6,
            'fibre' => 30,
        ],
    ],

    /* Maximum proportion by which a user can customise their personal daily intake amount by for each nutrient. */
    'customised_nutrient_boundary_factor' => 0.33,
];

?>